// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk9aClT4dy67-FhbMXalOw6mRqWsmDunE',
    appId: '1:886035718244:web:a542e8c916ad8a9effff71',
    messagingSenderId: '886035718244',
    projectId: 'plated-app-e8469',
    authDomain: 'plated-app-e8469.firebaseapp.com',
    storageBucket: 'plated-app-e8469.firebasestorage.app',
    measurementId: 'G-6HP2XWTCDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjxWehKwic1pmDahcFfsr3UzgK4sWQGeE',
    appId: '1:886035718244:android:46dc1660d4125dd0ffff71',
    messagingSenderId: '886035718244',
    projectId: 'plated-app-e8469',
    storageBucket: 'plated-app-e8469.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMQKG6EXix-9zqgqGh0KNqTfNaUG49Mg0',
    appId: '1:886035718244:ios:dc6d8481c9146ff2ffff71',
    messagingSenderId: '886035718244',
    projectId: 'plated-app-e8469',
    storageBucket: 'plated-app-e8469.firebasestorage.app',
    iosBundleId: 'com.example.platedAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMQKG6EXix-9zqgqGh0KNqTfNaUG49Mg0',
    appId: '1:886035718244:ios:dc6d8481c9146ff2ffff71',
    messagingSenderId: '886035718244',
    projectId: 'plated-app-e8469',
    storageBucket: 'plated-app-e8469.firebasestorage.app',
    iosBundleId: 'com.example.platedAppDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk9aClT4dy67-FhbMXalOw6mRqWsmDunE',
    appId: '1:886035718244:web:d705f7f75d2e7dfaffff71',
    messagingSenderId: '886035718244',
    projectId: 'plated-app-e8469',
    authDomain: 'plated-app-e8469.firebaseapp.com',
    storageBucket: 'plated-app-e8469.firebasestorage.app',
    measurementId: 'G-SWP5VZE9T2',
  );
}
